export enum ErrorCodes {
  SUCCESS = 'SUCCESS',
  ERR_EXEC_DB_FAIL = 'ERR_EXEC_DB_FAIL',
  ERR_JSON_FORMAT_FAIL = 'ERR_JSON_FORMAT_FAIL',
  ERR_DEPRECATED = 'ERR_DEPRECATED',
  ERR_NOT_IMPLEMENT = 'ERR_NOT_IMPLEMENT',
  ERR_EXCEPTION = 'ERR_EXCEPTION',
};
